name = "MyPkgDemo"
uuid = "427e7ede-6165-42f5-b323-3c8c11344767"
authors = ["junedwx"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
